<?php
/**
 * OffersApiTest
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kanastra Tech Hub
 *
 * The Kanastra Tech Hub solution is an API/application that ease the integration between parties of credit operations in general. From the credit originator, to the investor, until the debt collector and auditing processes.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: tech@kanastra.com.br
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the endpoint.
 */

namespace Swagger\Client;

use Swagger\Client\Configuration;
use Swagger\Client\ApiException;
use Swagger\Client\ObjectSerializer;
use PHPUnit\Framework\TestCase;

/**
 * OffersApiTest Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class OffersApiTest extends TestCase
{

    /**
     * Setup before running any test cases
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test case for apiCreditOriginatorsCreditOriginatorIdOffersBatchPost
     *
     * EN: Create offers from a batch. | PT: Cria offers a partir de um lote..
     *
     */
    public function testApiCreditOriginatorsCreditOriginatorIdOffersBatchPost()
    {
    }

    /**
     * Test case for apiCreditOriginatorsCreditOriginatorIdOffersExternalIdPatch
     *
     * EN: Update sponsor offer | PT: Atualiza o sacado da offer.
     *
     */
    public function testApiCreditOriginatorsCreditOriginatorIdOffersExternalIdPatch()
    {
    }

    /**
     * Test case for apiCreditOriginatorsCreditOriginatorIdOffersOfferIdInvalidPatch
     *
     * EN: Returns the status of the invalid offer | PT: Retorna o status da offer inválidada.
     *
     */
    public function testApiCreditOriginatorsCreditOriginatorIdOffersOfferIdInvalidPatch()
    {
    }

    /**
     * Test case for apiCreditOriginatorsCreditOriginatorIdOffersOfferIdOrExternalIdGet
     *
     * EN: Get the offer information | PT: Retorna as informações da oferta.
     *
     */
    public function testApiCreditOriginatorsCreditOriginatorIdOffersOfferIdOrExternalIdGet()
    {
    }

    /**
     * Test case for apiCreditOriginatorsCreditOriginatorIdOffersOfferIdPut
     *
     * EN: Update an offer. | PT: Atualiza uma offer..
     *
     */
    public function testApiCreditOriginatorsCreditOriginatorIdOffersOfferIdPut()
    {
    }

    /**
     * Test case for apiCreditOriginatorsCreditOriginatorIdOffersPost
     *
     * EN: Creates a new offer. | PT: Cria uma nova offer..
     *
     */
    public function testApiCreditOriginatorsCreditOriginatorIdOffersPost()
    {
    }

    /**
     * Test case for apiFundsFundIdCreditOriginatorsCreditOriginatorIdOffersDailyReportsDateGet
     *
     * EN: Get a return snapshot of all offers of the specified date | PT: Retorna um snapshot de todas offers recebidas na data especificada.
     *
     */
    public function testApiFundsFundIdCreditOriginatorsCreditOriginatorIdOffersDailyReportsDateGet()
    {
    }
}
