<?php
/**
 * SellerUpdatePerson
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kanastra Tech Hub
 *
 * The Kanastra Tech Hub solution is an API/application that ease the integration between parties of credit operations in general. From the credit originator, to the investor, until the debt collector and auditing processes.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: tech@kanastra.com.br
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * SellerUpdatePerson Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SellerUpdatePerson implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SellerUpdatePerson';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'person_type' => 'string',
        'asset_types' => 'string[]',
        'is_active' => 'bool',
        'phone' => 'string',
        'email' => 'string',
        'civil_state' => 'string',
        'profession' => 'string',
        'isolated_signature' => 'bool',
        'endorsement_signature' => 'bool',
        'assignment_term_signature' => 'bool',
        'address' => '\Swagger\Client\Model\SellerAddress',
        'bank_accounts' => '\Swagger\Client\Model\SellerBankAccount[]',
        'representatives' => '\Swagger\Client\Model\SellerRepresentative[]',
        'guarantors' => '\Swagger\Client\Model\SellerGuarantor[]',
        'custom_fields' => '\Swagger\Client\Model\SellerCustomField'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'person_type' => null,
        'asset_types' => null,
        'is_active' => null,
        'phone' => null,
        'email' => null,
        'civil_state' => null,
        'profession' => null,
        'isolated_signature' => null,
        'endorsement_signature' => null,
        'assignment_term_signature' => null,
        'address' => null,
        'bank_accounts' => null,
        'representatives' => null,
        'guarantors' => null,
        'custom_fields' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'person_type' => 'personType',
        'asset_types' => 'assetTypes',
        'is_active' => 'isActive',
        'phone' => 'phone',
        'email' => 'email',
        'civil_state' => 'civilState',
        'profession' => 'profession',
        'isolated_signature' => 'isolatedSignature',
        'endorsement_signature' => 'endorsementSignature',
        'assignment_term_signature' => 'assignmentTermSignature',
        'address' => 'address',
        'bank_accounts' => 'bankAccounts',
        'representatives' => 'representatives',
        'guarantors' => 'guarantors',
        'custom_fields' => 'customFields'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'person_type' => 'setPersonType',
        'asset_types' => 'setAssetTypes',
        'is_active' => 'setIsActive',
        'phone' => 'setPhone',
        'email' => 'setEmail',
        'civil_state' => 'setCivilState',
        'profession' => 'setProfession',
        'isolated_signature' => 'setIsolatedSignature',
        'endorsement_signature' => 'setEndorsementSignature',
        'assignment_term_signature' => 'setAssignmentTermSignature',
        'address' => 'setAddress',
        'bank_accounts' => 'setBankAccounts',
        'representatives' => 'setRepresentatives',
        'guarantors' => 'setGuarantors',
        'custom_fields' => 'setCustomFields'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'person_type' => 'getPersonType',
        'asset_types' => 'getAssetTypes',
        'is_active' => 'getIsActive',
        'phone' => 'getPhone',
        'email' => 'getEmail',
        'civil_state' => 'getCivilState',
        'profession' => 'getProfession',
        'isolated_signature' => 'getIsolatedSignature',
        'endorsement_signature' => 'getEndorsementSignature',
        'assignment_term_signature' => 'getAssignmentTermSignature',
        'address' => 'getAddress',
        'bank_accounts' => 'getBankAccounts',
        'representatives' => 'getRepresentatives',
        'guarantors' => 'getGuarantors',
        'custom_fields' => 'getCustomFields'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['person_type'] = isset($data['person_type']) ? $data['person_type'] : 'NATURAL_PERSON';
        $this->container['asset_types'] = isset($data['asset_types']) ? $data['asset_types'] : null;
        $this->container['is_active'] = isset($data['is_active']) ? $data['is_active'] : null;
        $this->container['phone'] = isset($data['phone']) ? $data['phone'] : '3432124453';
        $this->container['email'] = isset($data['email']) ? $data['email'] : 'contato@kanastra.com.br';
        $this->container['civil_state'] = isset($data['civil_state']) ? $data['civil_state'] : null;
        $this->container['profession'] = isset($data['profession']) ? $data['profession'] : null;
        $this->container['isolated_signature'] = isset($data['isolated_signature']) ? $data['isolated_signature'] : null;
        $this->container['endorsement_signature'] = isset($data['endorsement_signature']) ? $data['endorsement_signature'] : null;
        $this->container['assignment_term_signature'] = isset($data['assignment_term_signature']) ? $data['assignment_term_signature'] : null;
        $this->container['address'] = isset($data['address']) ? $data['address'] : null;
        $this->container['bank_accounts'] = isset($data['bank_accounts']) ? $data['bank_accounts'] : null;
        $this->container['representatives'] = isset($data['representatives']) ? $data['representatives'] : null;
        $this->container['guarantors'] = isset($data['guarantors']) ? $data['guarantors'] : null;
        $this->container['custom_fields'] = isset($data['custom_fields']) ? $data['custom_fields'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets person_type
     *
     * @return string
     */
    public function getPersonType()
    {
        return $this->container['person_type'];
    }

    /**
     * Sets person_type
     *
     * @param string $person_type The type of the seller.
     *
     * @return $this
     */
    public function setPersonType($person_type)
    {
        $this->container['person_type'] = $person_type;

        return $this;
    }

    /**
     * Gets asset_types
     *
     * @return string[]
     */
    public function getAssetTypes()
    {
        return $this->container['asset_types'];
    }

    /**
     * Sets asset_types
     *
     * @param string[] $asset_types Asset type. It can be:   - `DUPLICATA_MERCANTIL` - Mercantile duplicate  - `CHEQUE` - Check  - `CONTRATO_DIGITAL` - Digital contract  - `CONTRATO_FISICO` - Physical contract  - `MULTIPLOS` - Multiple  - `NOTA_SERVICOS` - Brazilian services invoice  - `CARTAO_CREDITO` - Credit card  - `DIREITOS_CREDITORIOS` - Debt rights  - `ARRANJO_PAGAMENTO` - Payment scheme  - `CEDULA_CREDITO_BANCARIO` - Bank credit note  - `CEDULA_PRODUTOR_RURAL_FINANCEIRA` - Financial Rural Producer Certificate  - `NOTA_COMERCIAL` - Commercial note  - `ASSISTENCIA_FINANCEIRA` - Financial Assistance  ---- Tipo do ativo. Valores possíveis são:   - `DUPLICATA_MERCANTIL` - Duplicata mercantil  - `CHEQUE` - Cheque  - `CONTRATO_DIGITAL` - Contrato digital  - `CONTRATO_FISICO` - Contrato físico  - `MULTIPLOS` - Múltiplos  - `NOTA_SERVICOS` - Nota Fiscal de Serviço  - `CARTAO_CREDITO` - Cartão de Crédito  - `DIREITOS_CREDITORIOS` - Direitos Creditórios  - `ARRANJO_PAGAMENTO` - Arranjo de pagamento  - `CEDULA_CREDITO_BANCARIO` - Cédula de Crédito Bancário  - `CEDULA_PRODUTOR_RURAL_FINANCEIRA` - Cédula de Produtor Rural Financeira  - `NOTA_COMERCIAL` - Nota comercial  - `ASSISTENCIA_FINANCEIRA` - Assistência Financeira
     *
     * @return $this
     */
    public function setAssetTypes($asset_types)
    {
        $this->container['asset_types'] = $asset_types;

        return $this;
    }

    /**
     * Gets is_active
     *
     * @return bool
     */
    public function getIsActive()
    {
        return $this->container['is_active'];
    }

    /**
     * Sets is_active
     *
     * @param bool $is_active is_active
     *
     * @return $this
     */
    public function setIsActive($is_active)
    {
        $this->container['is_active'] = $is_active;

        return $this;
    }

    /**
     * Gets phone
     *
     * @return string
     */
    public function getPhone()
    {
        return $this->container['phone'];
    }

    /**
     * Sets phone
     *
     * @param string $phone The seller' phone.
     *
     * @return $this
     */
    public function setPhone($phone)
    {
        $this->container['phone'] = $phone;

        return $this;
    }

    /**
     * Gets email
     *
     * @return string
     */
    public function getEmail()
    {
        return $this->container['email'];
    }

    /**
     * Sets email
     *
     * @param string $email The seller's email.
     *
     * @return $this
     */
    public function setEmail($email)
    {
        $this->container['email'] = $email;

        return $this;
    }

    /**
     * Gets civil_state
     *
     * @return string
     */
    public function getCivilState()
    {
        return $this->container['civil_state'];
    }

    /**
     * Sets civil_state
     *
     * @param string $civil_state Civil State of the representative
     *
     * @return $this
     */
    public function setCivilState($civil_state)
    {
        $this->container['civil_state'] = $civil_state;

        return $this;
    }

    /**
     * Gets profession
     *
     * @return string
     */
    public function getProfession()
    {
        return $this->container['profession'];
    }

    /**
     * Sets profession
     *
     * @param string $profession The profession of the representative
     *
     * @return $this
     */
    public function setProfession($profession)
    {
        $this->container['profession'] = $profession;

        return $this;
    }

    /**
     * Gets isolated_signature
     *
     * @return bool
     */
    public function getIsolatedSignature()
    {
        return $this->container['isolated_signature'];
    }

    /**
     * Sets isolated_signature
     *
     * @param bool $isolated_signature isolated_signature
     *
     * @return $this
     */
    public function setIsolatedSignature($isolated_signature)
    {
        $this->container['isolated_signature'] = $isolated_signature;

        return $this;
    }

    /**
     * Gets endorsement_signature
     *
     * @return bool
     */
    public function getEndorsementSignature()
    {
        return $this->container['endorsement_signature'];
    }

    /**
     * Sets endorsement_signature
     *
     * @param bool $endorsement_signature endorsement_signature
     *
     * @return $this
     */
    public function setEndorsementSignature($endorsement_signature)
    {
        $this->container['endorsement_signature'] = $endorsement_signature;

        return $this;
    }

    /**
     * Gets assignment_term_signature
     *
     * @return bool
     */
    public function getAssignmentTermSignature()
    {
        return $this->container['assignment_term_signature'];
    }

    /**
     * Sets assignment_term_signature
     *
     * @param bool $assignment_term_signature assignment_term_signature
     *
     * @return $this
     */
    public function setAssignmentTermSignature($assignment_term_signature)
    {
        $this->container['assignment_term_signature'] = $assignment_term_signature;

        return $this;
    }

    /**
     * Gets address
     *
     * @return \Swagger\Client\Model\SellerAddress
     */
    public function getAddress()
    {
        return $this->container['address'];
    }

    /**
     * Sets address
     *
     * @param \Swagger\Client\Model\SellerAddress $address address
     *
     * @return $this
     */
    public function setAddress($address)
    {
        $this->container['address'] = $address;

        return $this;
    }

    /**
     * Gets bank_accounts
     *
     * @return \Swagger\Client\Model\SellerBankAccount[]
     */
    public function getBankAccounts()
    {
        return $this->container['bank_accounts'];
    }

    /**
     * Sets bank_accounts
     *
     * @param \Swagger\Client\Model\SellerBankAccount[] $bank_accounts bank_accounts
     *
     * @return $this
     */
    public function setBankAccounts($bank_accounts)
    {
        $this->container['bank_accounts'] = $bank_accounts;

        return $this;
    }

    /**
     * Gets representatives
     *
     * @return \Swagger\Client\Model\SellerRepresentative[]
     */
    public function getRepresentatives()
    {
        return $this->container['representatives'];
    }

    /**
     * Sets representatives
     *
     * @param \Swagger\Client\Model\SellerRepresentative[] $representatives representatives
     *
     * @return $this
     */
    public function setRepresentatives($representatives)
    {
        $this->container['representatives'] = $representatives;

        return $this;
    }

    /**
     * Gets guarantors
     *
     * @return \Swagger\Client\Model\SellerGuarantor[]
     */
    public function getGuarantors()
    {
        return $this->container['guarantors'];
    }

    /**
     * Sets guarantors
     *
     * @param \Swagger\Client\Model\SellerGuarantor[] $guarantors guarantors
     *
     * @return $this
     */
    public function setGuarantors($guarantors)
    {
        $this->container['guarantors'] = $guarantors;

        return $this;
    }

    /**
     * Gets custom_fields
     *
     * @return \Swagger\Client\Model\SellerCustomField
     */
    public function getCustomFields()
    {
        return $this->container['custom_fields'];
    }

    /**
     * Sets custom_fields
     *
     * @param \Swagger\Client\Model\SellerCustomField $custom_fields custom_fields
     *
     * @return $this
     */
    public function setCustomFields($custom_fields)
    {
        $this->container['custom_fields'] = $custom_fields;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
