<?php
/**
 * SellerLegalPersonDocuments
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kanastra Tech Hub
 *
 * The Kanastra Tech Hub solution is an API/application that ease the integration between parties of credit operations in general. From the credit originator, to the investor, until the debt collector and auditing processes.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: tech@kanastra.com.br
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace Swagger\Client\Model;

use \ArrayAccess;
use \Swagger\Client\ObjectSerializer;

/**
 * SellerLegalPersonDocuments Class Doc Comment
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class SellerLegalPersonDocuments implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'SellerLegalPersonDocuments';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'llc_agreement' => 'string',
        'assignment_agreement' => 'string',
        'power_of_attorney' => 'string'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'llc_agreement' => 'binary',
        'assignment_agreement' => 'binary',
        'power_of_attorney' => 'binary'
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'llc_agreement' => 'llcAgreement',
        'assignment_agreement' => 'assignmentAgreement',
        'power_of_attorney' => 'powerOfAttorney'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'llc_agreement' => 'setLlcAgreement',
        'assignment_agreement' => 'setAssignmentAgreement',
        'power_of_attorney' => 'setPowerOfAttorney'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'llc_agreement' => 'getLlcAgreement',
        'assignment_agreement' => 'getAssignmentAgreement',
        'power_of_attorney' => 'getPowerOfAttorney'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['llc_agreement'] = isset($data['llc_agreement']) ? $data['llc_agreement'] : null;
        $this->container['assignment_agreement'] = isset($data['assignment_agreement']) ? $data['assignment_agreement'] : null;
        $this->container['power_of_attorney'] = isset($data['power_of_attorney']) ? $data['power_of_attorney'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets llc_agreement
     *
     * @return string
     */
    public function getLlcAgreement()
    {
        return $this->container['llc_agreement'];
    }

    /**
     * Sets llc_agreement
     *
     * @param string $llc_agreement llc_agreement
     *
     * @return $this
     */
    public function setLlcAgreement($llc_agreement)
    {
        $this->container['llc_agreement'] = $llc_agreement;

        return $this;
    }

    /**
     * Gets assignment_agreement
     *
     * @return string
     */
    public function getAssignmentAgreement()
    {
        return $this->container['assignment_agreement'];
    }

    /**
     * Sets assignment_agreement
     *
     * @param string $assignment_agreement assignment_agreement
     *
     * @return $this
     */
    public function setAssignmentAgreement($assignment_agreement)
    {
        $this->container['assignment_agreement'] = $assignment_agreement;

        return $this;
    }

    /**
     * Gets power_of_attorney
     *
     * @return string
     */
    public function getPowerOfAttorney()
    {
        return $this->container['power_of_attorney'];
    }

    /**
     * Sets power_of_attorney
     *
     * @param string $power_of_attorney power_of_attorney
     *
     * @return $this
     */
    public function setPowerOfAttorney($power_of_attorney)
    {
        $this->container['power_of_attorney'] = $power_of_attorney;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
