<?php
/**
 * BatchOfferTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kanastra Tech Hub
 *
 * The Kanastra Tech Hub solution is an API/application that ease the integration between parties of credit operations in general. From the credit originator, to the investor, until the debt collector and auditing processes.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: tech@kanastra.com.br
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * BatchOfferTest Class Doc Comment
 *
 * @category    Class
 * @description BatchOffer
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BatchOfferTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BatchOffer"
     */
    public function testBatchOffer()
    {
    }

    /**
     * Test attribute "seller_name"
     */
    public function testPropertySellerName()
    {
    }

    /**
     * Test attribute "seller_person_type"
     */
    public function testPropertySellerPersonType()
    {
    }

    /**
     * Test attribute "seller_government_id"
     */
    public function testPropertySellerGovernmentId()
    {
    }

    /**
     * Test attribute "seller_external_code"
     */
    public function testPropertySellerExternalCode()
    {
    }

    /**
     * Test attribute "seller_address"
     */
    public function testPropertySellerAddress()
    {
    }

    /**
     * Test attribute "seller_address_number"
     */
    public function testPropertySellerAddressNumber()
    {
    }

    /**
     * Test attribute "seller_address_complement"
     */
    public function testPropertySellerAddressComplement()
    {
    }

    /**
     * Test attribute "seller_neighborhood"
     */
    public function testPropertySellerNeighborhood()
    {
    }

    /**
     * Test attribute "seller_city"
     */
    public function testPropertySellerCity()
    {
    }

    /**
     * Test attribute "seller_state"
     */
    public function testPropertySellerState()
    {
    }

    /**
     * Test attribute "seller_country"
     */
    public function testPropertySellerCountry()
    {
    }

    /**
     * Test attribute "seller_zip_code"
     */
    public function testPropertySellerZipCode()
    {
    }

    /**
     * Test attribute "seller_bank"
     */
    public function testPropertySellerBank()
    {
    }

    /**
     * Test attribute "seller_agency"
     */
    public function testPropertySellerAgency()
    {
    }

    /**
     * Test attribute "seller_agency_digit"
     */
    public function testPropertySellerAgencyDigit()
    {
    }

    /**
     * Test attribute "seller_account"
     */
    public function testPropertySellerAccount()
    {
    }

    /**
     * Test attribute "seller_account_digit"
     */
    public function testPropertySellerAccountDigit()
    {
    }

    /**
     * Test attribute "coobrigation"
     */
    public function testPropertyCoobrigation()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "items"
     */
    public function testPropertyItems()
    {
    }
}
