<?php
/**
 * BatchOfferItemsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kanastra Tech Hub
 *
 * The Kanastra Tech Hub solution is an API/application that ease the integration between parties of credit operations in general. From the credit originator, to the investor, until the debt collector and auditing processes.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: tech@kanastra.com.br
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * BatchOfferItemsTest Class Doc Comment
 *
 * @category    Class
 * @description BatchOfferItems
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class BatchOfferItemsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "BatchOfferItems"
     */
    public function testBatchOfferItems()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "sponsor_name"
     */
    public function testPropertySponsorName()
    {
    }

    /**
     * Test attribute "sponsor_person_type"
     */
    public function testPropertySponsorPersonType()
    {
    }

    /**
     * Test attribute "sponsor_government_id"
     */
    public function testPropertySponsorGovernmentId()
    {
    }

    /**
     * Test attribute "sponsor_external_code"
     */
    public function testPropertySponsorExternalCode()
    {
    }

    /**
     * Test attribute "sponsor_address"
     */
    public function testPropertySponsorAddress()
    {
    }

    /**
     * Test attribute "sponsor_address_number"
     */
    public function testPropertySponsorAddressNumber()
    {
    }

    /**
     * Test attribute "sponsor_address_complement"
     */
    public function testPropertySponsorAddressComplement()
    {
    }

    /**
     * Test attribute "sponsor_neighborhood"
     */
    public function testPropertySponsorNeighborhood()
    {
    }

    /**
     * Test attribute "sponsor_city"
     */
    public function testPropertySponsorCity()
    {
    }

    /**
     * Test attribute "sponsor_state"
     */
    public function testPropertySponsorState()
    {
    }

    /**
     * Test attribute "sponsor_country"
     */
    public function testPropertySponsorCountry()
    {
    }

    /**
     * Test attribute "sponsor_zip_code"
     */
    public function testPropertySponsorZipCode()
    {
    }

    /**
     * Test attribute "sponsor_bank"
     */
    public function testPropertySponsorBank()
    {
    }

    /**
     * Test attribute "sponsor_agency"
     */
    public function testPropertySponsorAgency()
    {
    }

    /**
     * Test attribute "sponsor_agency_digit"
     */
    public function testPropertySponsorAgencyDigit()
    {
    }

    /**
     * Test attribute "sponsor_account"
     */
    public function testPropertySponsorAccount()
    {
    }

    /**
     * Test attribute "sponsor_account_digit"
     */
    public function testPropertySponsorAccountDigit()
    {
    }

    /**
     * Test attribute "sponsor_pix_key"
     */
    public function testPropertySponsorPixKey()
    {
    }

    /**
     * Test attribute "asset_type"
     */
    public function testPropertyAssetType()
    {
    }

    /**
     * Test attribute "invoice_number"
     */
    public function testPropertyInvoiceNumber()
    {
    }

    /**
     * Test attribute "invoice_date"
     */
    public function testPropertyInvoiceDate()
    {
    }

    /**
     * Test attribute "invoice_key"
     */
    public function testPropertyInvoiceKey()
    {
    }

    /**
     * Test attribute "total_installments"
     */
    public function testPropertyTotalInstallments()
    {
    }

    /**
     * Test attribute "payment_value"
     */
    public function testPropertyPaymentValue()
    {
    }

    /**
     * Test attribute "payment_date"
     */
    public function testPropertyPaymentDate()
    {
    }

    /**
     * Test attribute "custom_fields"
     */
    public function testPropertyCustomFields()
    {
    }

    /**
     * Test attribute "files"
     */
    public function testPropertyFiles()
    {
    }

    /**
     * Test attribute "installments"
     */
    public function testPropertyInstallments()
    {
    }
}
