<?php
/**
 * OfferDetailsResponseTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  Swagger\Client
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Kanastra Tech Hub
 *
 * The Kanastra Tech Hub solution is an API/application that ease the integration between parties of credit operations in general. From the credit originator, to the investor, until the debt collector and auditing processes.
 *
 * OpenAPI spec version: 1.1.0
 * Contact: tech@kanastra.com.br
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.50
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace Swagger\Client;

use PHPUnit\Framework\TestCase;

/**
 * OfferDetailsResponseTest Class Doc Comment
 *
 * @category    Class
 * @description OfferDetailsResponse
 * @package     Swagger\Client
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class OfferDetailsResponseTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass(): void
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp(): void
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown(): void
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass(): void
    {
    }

    /**
     * Test "OfferDetailsResponse"
     */
    public function testOfferDetailsResponse()
    {
    }

    /**
     * Test attribute "id"
     */
    public function testPropertyId()
    {
    }

    /**
     * Test attribute "status"
     */
    public function testPropertyStatus()
    {
    }

    /**
     * Test attribute "buyer_id"
     */
    public function testPropertyBuyerId()
    {
    }

    /**
     * Test attribute "sponsor_id"
     */
    public function testPropertySponsorId()
    {
    }

    /**
     * Test attribute "seller_id"
     */
    public function testPropertySellerId()
    {
    }

    /**
     * Test attribute "created_at"
     */
    public function testPropertyCreatedAt()
    {
    }

    /**
     * Test attribute "updated_at"
     */
    public function testPropertyUpdatedAt()
    {
    }

    /**
     * Test attribute "credit_originator_id"
     */
    public function testPropertyCreditOriginatorId()
    {
    }

    /**
     * Test attribute "external_id"
     */
    public function testPropertyExternalId()
    {
    }

    /**
     * Test attribute "daily_discount_rate"
     */
    public function testPropertyDailyDiscountRate()
    {
    }

    /**
     * Test attribute "daily_discount_rate_observations"
     */
    public function testPropertyDailyDiscountRateObservations()
    {
    }

    /**
     * Test attribute "daily_discount_rate_calculator"
     */
    public function testPropertyDailyDiscountRateCalculator()
    {
    }

    /**
     * Test attribute "daily_discount_rate_calculated_at"
     */
    public function testPropertyDailyDiscountRateCalculatedAt()
    {
    }

    /**
     * Test attribute "daily_discount_rate_apply_on"
     */
    public function testPropertyDailyDiscountRateApplyOn()
    {
    }

    /**
     * Test attribute "payment_value"
     */
    public function testPropertyPaymentValue()
    {
    }

    /**
     * Test attribute "installments"
     */
    public function testPropertyInstallments()
    {
    }

    /**
     * Test attribute "validations"
     */
    public function testPropertyValidations()
    {
    }
}
